replicaCount: 1

image:
  repository: photography-backend
  pullPolicy: Never
  tag: "latest"

env:
  PHOTO_DATA_PATH: "/app/resources/photoInfo.json"
  HOST: "0.0.0.0"
  PORT: "8080"

containerPort: 8080

nameOverride: ""
fullnameOverride: ""

serviceAccount:
  create: true
  automount: true
  annotations: {}
  name: ""

podAnnotations: {}
podLabels: {}

podSecurityContext: {}

securityContext: {}

service:
  type: NodePort
  port: 8080
  targetPort: 8080
  nodePort: 30002

ingress:
  enabled: true
  className: "nginx"
  annotations:
    nginx.ingress.kubernetes.io/proxy-buffering: "on"
    nginx.ingress.kubernetes.io/configuration-snippet: |
      expires 24h;
      add_header Cache-Control "public, no-transform";
      add_header X-Cache-Status "CACHED";
  hosts:
    - host: photography-portfolio.local
      paths:
        - path: /api/v1/photos/image
          pathType: Prefix
        - path: /
          pathType: Prefix
  tls: []

resources: {}

livenessProbe: {}
readinessProbe: {}

autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 100
  targetCPUUtilizationPercentage: 80

volumes: []

volumeMounts: []

nodeSelector: {}

tolerations: []

affinity: {}
